In [ ]:
import pandas as pd

In [ ]:

df = pd.read_csv('business-operations-survey-2022-business-finance (1).csv', encoding='latin1')

In [ ]:
df

,description,industry,level,size,line_code,value
0,Type of outstanding debt: bank overdrafts,total,0,619 employees,D0201,13215
1,Type of outstanding debt: bank overdrafts,total,0,2049 employees,D0201,3405
2,Type of outstanding debt: bank overdrafts,total,0,5099 employees,D0201,978
3,Type of outstanding debt: bank overdrafts,total,0,100+ employees,D0201,687
4,Type of outstanding debt: bank overdrafts,"Agriculture, forestry, & fishing",1,total,D0201,1974
...,...,...,...,...,...,...
6622,Number of years business is dealing with main ...,Education & training,1,total,D2100.04,468
6623,Number of years business is dealing with main ...,Health care & social assistance,1,total,D2100.04,1320
6624,Number of years business is dealing with main ...,Arts & recreation services,1,total,D2100.04,264
6625,Number of years business is dealing with main ...,Other services,1,total,D2100.04,936
6626,Number of years business is dealing with main ...,total,0,total,D2100.04,24012

CSV file from url

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# Sep parameter

index col parameter

In [ ]:
pd.read_csv('titanic.tsv', sep='\t',names=['sno','1st', '2nd','3rd','4th','5th', '6th','7th','8th','9th','10th'])

,sno,1st,2nd,3rd,4th,5th,6th,7th,8th,9th,10th
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,\N,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,\N,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,\N,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,\N,S
888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,\N,1,2,W./C. 6607,23.4500,\N,S
890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,\N,Q

index col parameter

In [ ]:
df = pd.read_csv('data.csv')
print(df.columns.tolist())

['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC', 'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name', 'Variable_category', 'Value', 'Industry_code_ANZSIC06']

In [ ]:

df = pd.read_csv(
    'data.csv',
    encoding='latin1',
    index_col=0,
)
df.head()

,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
ï»¿Year,,,,,,,,,
2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...

Header parameter

In [ ]:
pd.read_csv('data.csv', header=0)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
60250,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60251,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60252,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60253,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60254,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

using cols parameter
is used for showing specific colums , it helps to reduce the runtime

In [ ]:
df = pd.read_csv(
    'data.csv',
    encoding='utf-8-sig',
    usecols=['Year', 'Value', 'Variable_name']
)
df.head()

   Year                                    Variable_name   Value
0  2025                                     Total income  976077
1  2025  Sales, government funding, grants and subsidies  854561
2  2025                Interest, dividends and donations   96238
3  2025                             Non-operating income   25279
4  2025                                Total expenditure  867750

The primary purpose of squeeze is dimensionality reduction—removing redundant 1-dimensional axes to convert a data structure into its simplest underlying format.

In [ ]:
import pandas as pd

# ১টি কলাম usecols দিয়ে ফিল্টার করে .squeeze('columns') কল করুন
series = pd.read_csv(
    'data.csv',
    encoding='utf-8-sig',
    usecols=['Year']
).squeeze('columns')

print(type(series))  # <class 'pandas.core.series.Series'>
series.head()

<class 'pandas.core.series.Series'>

0    2025
1    2025
2    2025
3    2025
4    2025
Name: Year, dtype: int64

In [ ]:
# Skip the first 2 rows of the file
df = pd.read_csv('data.csv', skiprows=2)

# Skip specific row indices (e.g., row 0, 2, and 5)
df = pd.read_csv('data.csv', skiprows=[0, 2, 5])

# Skip using a lambda function (e.g., skip all even-indexed rows)
df = pd.read_csv('data.csv', skiprows=lambda x: x % 2 == 0)

df

,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,"ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)"
0,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,9483,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,160833,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,1702,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
30122,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H33,Other liabilities,Financial position,"2,220","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
30123,2013,Level 3,ZZ11,Food product manufacturing,Dollars,H35,Surplus per employee count,Financial ratios,"17,700","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
30124,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
30125,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
30126,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [ ]:
# Read only the first 100 rows
df = pd.read_csv('data.csv', nrows=100)
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
95,2025,Level 4,AA111,Horticulture and Fruit Growing,Dollars (millions),H07,Non-operating income,Financial performance,195,"ANZSIC06 groups A011, A012, and A013"
96,2025,Level 4,AA111,Horticulture and Fruit Growing,Dollars (millions),H08,Total expenditure,Financial performance,5794,"ANZSIC06 groups A011, A012, and A013"
97,2025,Level 4,AA111,Horticulture and Fruit Growing,Dollars (millions),H09,Interest and donations,Financial performance,446,"ANZSIC06 groups A011, A012, and A013"
98,2025,Level 4,AA111,Horticulture and Fruit Growing,Dollars (millions),H10,Indirect taxes,Financial performance,51,"ANZSIC06 groups A011, A012, and A013"
99,2025,Level 4,AA111,Horticulture and Fruit Growing,Dollars (millions),H11,Depreciation,Financial performance,413,"ANZSIC06 groups A011, A012, and A013"

In [ ]:
# Skip corrupted lines instead of crashing
df = pd.read_csv('data.csv', on_bad_lines='skip')
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
60250,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60251,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60252,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60253,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60254,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60255 entries, 0 to 60254
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         60255 non-null  int64
 1   Industry_aggregation_NZSIOC  60255 non-null  object
 2   Industry_code_NZSIOC         60255 non-null  object
 3   Industry_name_NZSIOC         60255 non-null  object
 4   Units                        60255 non-null  object
 5   Variable_code                60255 non-null  object
 6   Variable_name                60255 non-null  object
 7   Variable_category            60255 non-null  object
 8   Value                        60255 non-null  object
 9   Industry_code_ANZSIC06       60255 non-null  object
dtypes: int64(1), object(9)
memory usage: 4.6+ MB

we can change the datatypes if needed by calling dtypes parameter

The converters parameter lets you apply custom Python functions to specific columns while the CSV is being read.

In [ ]:


# Define transformation functions
def clean_currency(val):
    return float(val.replace('$', '').replace(',', ''))

def clean_name(val):
    return val.strip().title()

# Apply converters during load
df = pd.read_csv(
    'data.csv',
    converters={
        'Salary': clean_currency,
        'Full_Name': clean_name
    }
)
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
60250,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60251,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60252,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60253,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60254,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [ ]:


chunk_size = 50_000  # Number of rows per batch


for i, chunk in enumerate(pd.read_csv('data.csv', chunksize=chunk_size)):
    total_rows += len(chunk)
    print(f"Batch {i + 1}: Processed {len(chunk)} rows (Cumulative: {total_rows:,})")

print(f"\nFinal Total Rows: {total_rows:,}")

Batch 1: Processed 50000 rows (Cumulative: 50,000)
Batch 2: Processed 10255 rows (Cumulative: 60,255)

Final Total Rows: 60,255